database:
  datasource:
    primary:
      jdbcUrl: "jdbc:postgresql://localhost:5432/api-gateway"
      username: "api-gateway-admin"
      password: "SQL"
      poolName: "primary"
      maximumPoolSize: "10"
      minimumIdle: "1"
      connectionTimeout: "250"
    liquibase:
      jdbcUrl: "jdbc:postgresql://localhost:5432/api-gateway"
      username: "api-gateway-admin"
      password: "SQL"
      poolName: "liquibase"
      maximumPoolSize: "1"
      minimumIdle: "0"

management:
  endpoints:
    enabled-by-default: "false"
    web.exposure.include: "prometheus"
  endpoint:
    prometheus.enabled: "true"

server:
  port: 8080
