version: "3"
services:
  prometheus:
    image: "prom/prometheus"
    ports:
      - "9090:9090"
    network_mode: "host"
    volumes:
      - "./prometheus:/etc/prometheus/"

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    network_mode: "host"
    depends_on:
      - prometheus

  kibana:
    image: "kibana:7.7.0"
    ports:
      - "5601:5601"
    environment:
      - "discovery.type=single-node"

  elasticsearch:
    image: "elasticsearch:7.7.0"
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "discovery.type=single-node"

  logstash:
    image: "logstash:7.7.0"
    command: 'logstash -e "input { beats { port => 5044 } } output { elasticsearch { hosts => elasticsearch } }"'

  filebeat:
    image: "docker.elastic.co/beats/filebeat:7.7.1"
    volumes:
      - "./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  db-admin:
    image: "dpage/pgadmin4"
    ports:
      - "5431:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"

  db-api-gateway:
    image: "postgres:11.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "api-gateway"
      POSTGRES_USER: "api-gateway-admin"
      POSTGRES_PASSWORD: "SQL"