version: "3"
services:
  db-admin:
    image: "dpage/pgadmin4"
    ports:
      - "5431:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@postgres.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
  db-api-gateway:
    image: "postgres:11.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "api-gateway"
      POSTGRES_USER: "api-gateway-admin"
      POSTGRES_PASSWORD: "SQL"